name: 'TEI validation'
description: 'Validate XML documents against TEI schema'
inputs:
  tei-version:
    description: 'TEI version to validate against'
    required: false
    default: '4.7.0'
  tei-files:
    description: 'path or pattern to TEI files'
    required: false
    default: 'tei/*.xml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tei-version }}
    - ${{ inputs.tei-files }}
