name: "TEI validation"
description: "Validate XML documents against TEI schema"
inputs:
  schema:
    description: "Schema to validate against"
    required: false
    default: "all"
  version:
    description: "Schema version to validate against"
    required: false
    default: ""
  files:
    description: "Path or pattern to TEI files"
    required: false
    default: "tei/*.xml"
  fatal:
    description: "Exit with error code when validation fails"
    required: false
    default: "yes"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.schema }}
    - ${{ inputs.version }}
    - ${{ inputs.files }}
