name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Action Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test Default Inputs
        id: test-default
        uses: ./
        with:
          fatal: no

      - name: Test Valid File
        id: test-valid
        uses: ./
        with:
          tei-files: tei/valid.xml

      - name: Test No Files
        id: test-no-files
        uses: ./
        with:
          tei-files: tei/nosuchfile*
